import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { StoreProvider } from './StoreProvider';
import { UiProvider } from './UiProviders';
import './globals.css';
import { NavBar } from './navBar';
import './theme-config.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  title: 'Next NTV App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.variable}>
        <StoreProvider>
          <UiProvider>
            <NavBar></NavBar>
            <main className='p-3'>{children}</main>
          </UiProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
